# Generated by Django 5.1.2 on 2024-10-27 14:23

import social.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to=social.models.post_image_file_path),
        ),
    ]
