# Generated by Django 5.1.2 on 2024-10-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='scheduled_time',
            field=models.DateTimeField(null=True),
        ),
    ]
