# Generated by Django 5.1.2 on 2024-11-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
