# Generated by Django 5.1.2 on 2024-11-04 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_follow'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following')},
        ),
    ]
